const game = [
	{
		id: 'g_01',
		image: process.env.PUBLIC_URL+'/images/g01.jpg',
		name: 'HI-FI RUSH',
		tag01:'액션',
		tag02:'리듬',
		tag03:'액션 어드벤처',
		tag04:'싱글',
		tag05:'플랫폼',
    tag06:'new',
		date:'2023년 1월 26일',
		desc:'락 스타 지망생 차이가 되어 비트를 타고, 오합지졸 팀과 함께 사악한 거대 기업을 상대로 요란한 리듬 전투를 벌이세요! Tango Gameworks에서 세계 전체가 음악과 싱크하는 새로운 액션 게임 Hi-Fi RUSH를 선보입니다.',
		price:34200,
		discount:0,
	},
	{
		id: 'g_02',
		image: process.env.PUBLIC_URL+'/images/g02.jpg',
		name: "TOM CLANCY'S GHOST RECON® BREAKPOINT",
		tag01: '액션',
		tag02: '어드벤처',
		tag03: '슈팅',
		tag04: '3인칭 슈팅',
		tag05: '멀티플레이어',
    tag06: 'new',
		date: '2023년 1월 24일',
		desc: "최신 Tom Clancy's Ghost Recon에서 고스트가 되어 울브즈라는 악당 특수 요원 무리에 맞서 싸우십시오!",
		price: 13000,
		discount: 0.8,
	},
	{
		id: 'g_03',
		image: process.env.PUBLIC_URL+'/images/g03.jpg',
		name: "DEAD SPACE",
		tag01: '공포',
		tag02: '3인칭 슈팅',
		tag03: '우주',
		tag04: '슈팅',
		tag05: '공상과학',
    tag06: 'new',
		date: '2023년 1월 28일',
		desc: "SF 서바이벌 호러 클래식 게임이 돌아옵니다! 완전히 재구성되어 원작 게임의 스릴 넘치는 세계관을 충실히 구현하는 동시에 개선된 그래픽, 오디오, 게임플레이로 더욱 몰입도 높은 경험을 제공합니다.",
		price: 66000,
		discount: 0,
	},
	{
		id: 'g_04',
		image: process.env.PUBLIC_URL+'/images/g04.jpg',
		name: "	WATCH DOGS®: LEGION",
		tag01: '액션',
		tag02: '어드벤처',
		tag03: '슈팅',
		tag04: 'RPG',
		tag05: '오픈월드',
    tag06: 'best',
		date: '2023년 1월 27일',
		desc: "Watch Dogs: Legion에서는 레지스탕스를 결성하고 몰락하기 직전인 근미래의 런던을 되찾아야 합니다.",
		price: 65000,
		discount: 0.8,
	},
	{
		id: 'g_05',
		image: process.env.PUBLIC_URL+'/images/g05.jpg',
		name: "PIZZA TOWER",
		tag01: '2D',
		tag02: '액션',
		tag03: '만화',
		tag04: '플랫폼',
		tag05: '코미디',
    tag06: 'new',
		date: '2023년 1월 27일',
		desc: "Pizza Tower is a fast paced 2D platformer inspired by the Wario Land series, with an emphasis on movement, exploration and score attack. Featuring highly stylized pixel art inspired by the cartoons from the '90s, and a highly energetic",
		price: 21500,
		discount: 0,
	},
	{
		id: 'g_06',
		image: process.env.PUBLIC_URL+'/images/g06.jpg',
		name: "WARLANDER",
		tag01: '전술 RPG',
		tag02: '핵 앤 슬래시',
		tag03: 'MOBA',
		tag04: 'PvP',
		tag05: '경쟁',
		tag06: 'best',
		date: '2023년 1월 25일',
		desc: "신과 같은 전사, 성직자, 마법사의 강력한 능력을 휘두르세요. 중세 느낌의 설정을 더한 독특한 스타일, 환상적인 아이템과 능력, 그리고 강력한 로봇까지 등장합니다! 공성 무기와 대재앙 주문을 사용하여 전장을 제어하고 적의 코어를 파괴하세요!",
		price: 0,
		discount: 0,
	},
	{
		id: 'g_07',
		image: process.env.PUBLIC_URL+'/images/g07.jpg',
		name: "FORSPOKEN",
		tag01: '탐험',
		tag02: '오픈 월드',
		tag03: '여주인공',
		tag04: '파쿠르',
		tag05: 'RPG',
		tag06: 'best',
		date: '2023년 1월 25일',
		desc: "FORSPOKEN은 아름답고 잔혹한 땅, 아시아로 오게 된 젊은 뉴요커 프레이의 여정을 그립니다. 집으로 돌아갈 방법을 알아내고자 프레이는 광활한 세계를 가로지르며, 흉포한 괴생명체와 맞서 싸우기 위해 새롭게 눈뜬 마법을 구사합니다.",
		price: 79800,
		discount: 0,
	},
	{
		id: 'g_08',
		image: process.env.PUBLIC_URL+'/images/g08.jpg',
		name: "TOM CLANCY’S THE DIVISION® 2",
		tag01: '액션',
		tag02: '어드벤처',
		tag03: '멀티플레이어',
		tag04: '3인칭',
		tag05: '슈팅',
		tag06: 'best',
		date: '2023년 1월 25일',
		desc: "역사가 기억하리라 Tom Clancy’s The Division®2에서 자유세계의 운명이 위기에 빠지게 됩니다. 엘리트 요원 팀을 이끌어 세계 유행병이 번진 이후의 워싱턴 DC의 질서를 복구하고 도시의 붕괴를 막아내십시오.",
		price: 33000,
		discount: 0,
	},
	{
		id: 'g_09',
		image: process.env.PUBLIC_URL+'/images/g09.jpg',
		name: "VOLZERK : MONSTERS AND LANDS UNKNOWN",
		tag01: '액션',
		tag02: 'RPG',
		tag03: '3D',
		tag04: '컬렉터톤',
		tag05: '탐험',
    tag06: 'new',
		date: '2023년 1월 25일',
		desc: "Monster Crossbreeding & Action RPG. Explore the world and raise legend monsters!",
		price: 0,
		discount: 0,
	},
	{
		id: 'g_10',
		image: process.env.PUBLIC_URL+'/images/g10.jpg',
		name: "GRAND THEFT AUTO: SAN ANDREAS – THE DEFINITIVE EDITION",
		tag01: '액션',
		tag02: '3인칭 슈팅',
		tag03: '어드벤처',
		tag04: '오픈 월드',
		tag05: '액션',
		tag06: 'best',
		date: '2023년 1월 25일',
		desc: "Grand Theft Auto: San Andreas: 이제 시대는 90년대 초, 칼이 도시로 돌아오자마자 두 명의 부패한 경찰들이 그에게 살인 누명을 씌웁니다. 칼 존슨(일명 'CJ')은 가족을 구하고 거리를 장악하기 위해 산 안드레아스 주 전체를 누비는 여행을 떠날 수밖에...",
		price: 65000,
		discount: 0.5,
	},
	{
		id: 'g_11',
		image: process.env.PUBLIC_URL+'/images/g11.jpg',
		name: "MARVEL’S SPIDER-MAN: MILES MORALES",
		tag01: '액션',
		tag02: '어드벤처',
		tag03: '오픈 월드',
		tag04: '슈퍼 히어로',
		tag05: '싱글 플레이어',
		tag06: 'best',
		date: '2022년 11월 19일',
		desc: "Marvel’s Spider-Man Remastered의 사건 이후, 십대 청소년 마일즈 모랄레스는 새로운 집에 적응하면서 멘토인 피터 파커의 발자취를 따라 새로운 스파이더맨이 됩니다. 하지만 무시무시한 힘겨루기로 인해 새로운 고향이 산산조각날 위기에 처하자...",
		price: 44800,
		discount: 0,
	},
	{
		id: 'g_12',
		image: process.env.PUBLIC_URL+'/images/g12.jpg',
		name: "NEED FOR SPEED™ UNBOUND",
		tag01: '레이싱',
		tag02: '액션',
		tag03: '멀티플레이어',
		tag04: '캐릭터 커스터마이즈',
		tag05: '오픈 월드',
		tag06: 'best',
		date: '2022년 12월 2일',
		desc: "정상으로 레이스하고, 주저앉지 마세요. 경찰을 따돌리고, 주간 예선전에 도전해 Lakeshore 최고의 스트리트 레이스인 The Grand에 입장하세요. 정교하게 튜닝된 커스텀 차량으로 차고를 가득 채우고, 자신만의 스타일로 거리를 빛내세요.",
		price: 77000,
		discount: 0.5,
	},
	{
		id: 'g_13',
		image: process.env.PUBLIC_URL+'/images/g13.jpg',
		name: "NO ONE SURVIVED",
		tag01: '탐험',
		tag02: '생존',
		tag03: '좀비',
		tag04: '멀티플레이어',
		tag05: '3인칭',
		tag06: 'new',
		date: '2023년 1월 14일',
		desc: "This is a multiplayer cooperative open world construction survival sandbox game, where you and your friends must find supplies and build shelters in this world. You have to keep an eye on your character's needs state at all times, a bad state.",
		price: 18500,
		discount: 0,
	},
	{
		id: 'g_14',
		image: process.env.PUBLIC_URL+'/images/g14.jpg',
		name: "ALICE ESCAPED!",
		tag01: '분위기',
		tag02: '어드벤처',
		tag03: '플랫폼',
		tag04: '메트로배니아',
		tag05: '풍부한 스토리',
		tag06: 'best',
		date: '2023년 1월 28일',
		desc: "Explore the stylish world of Wonderland with Usada and Kotora as they search for a mysterious girl named Alice! A Metroidvania action game with a rich, exhilarating battle system all wrapped up in cuteness!",
		price: 21500,
		discount: 0.1,
	},
	{
		id: 'g_15',
		image: process.env.PUBLIC_URL+'/images/g15.jpg',
		name: "CRISIS CORE –FINAL FANTASY VII– REUNION",
		tag01: '액션',
		tag02: 'RPG',
		tag03: '어드벤처',
		tag04: 'JRPG',
		tag05: 'RPG',
		tag06: 'best',
		date: '2022년 12월 14일',
		desc: "	FFVII의 이전 이야기가 그려지는 『CRISIS CORE -FINAL FANTASY VII-』가 단순한 HD 리마스터에 머무르지 않는 진화를 이루었습니다. 그래픽의 HD화는 물론, 배틀 시스템의 개량이나 풀 보이스 대응 등 신규 요소를 추가하여 감동적인 스토리가 화려하게 펼쳐진다.",
		price: 62000,
		discount: 0.1,
	},
	{
		id: 'g_16',
		image: process.env.PUBLIC_URL+'/images/g16.jpg',
		name: "ASSASSIN'S CREED VALHALLA",
		tag01: '액션',
		tag02: '오픈 월드',
		tag03: '어드벤처',
		tag04: 'RPG',
		tag05: '싱글 플레이어',
		tag06: 'new',
		date: '2022년 12월 7일',
		desc: "전설적인 바이킹 습격자로 명성을 위해 싸우십시오. 적들을 습격하고, 정착지를 개척하고, 정치적인 역량을 키워나가야 합니다.",
		price: 65000,
		discount: 0,
	},
	{
		id: 'g_17',
		image: process.env.PUBLIC_URL+'/images/g17.jpg',
		name: "	RETURN TO ABYSS 重返深渊",
		tag01: '어드벤처',
		tag02: '액션',
		tag03: '액션 로그라이크',
		tag04: 'RPG',
		tag05: '스토리',
		tag06: 'best',
		date: '2023년 1월 7일',
		desc: "Return to Abyss is a mowing survival game with Rogue-Lite elements, upgrade your weapons and use your fighting skills to fight through over 10,000 monsters on screen until defeat the culprit who broght chaos!",
		price: 5600,
		discount: 0,
	},
	{
		id: 'g_18',
		image: process.env.PUBLIC_URL+'/images/g18.jpg',
		name: "WARHAMMER 40,000: DARKTIDE",
		tag01: '고어',
		tag02: '어드벤처',
		tag03: '온라인',
		tag04: '멀티플레이어',
		tag05: '액션',
		tag06: 'new',
		date: '2022년 12월 1일',
		desc: "이 격렬하고 잔혹한 액션 슈팅 게임에서 피에 굶주린 적들로부터 테르티움을 되찾으세요. Warhammer 40,000: Darktide는 Vermintide 시리즈로 상을 받은 팀이 선보이는 새로운 협동 중심의 경험입니다. 테르티움이 몰락하면 이교도들이 일어날 것입니다.",
		price: 44000,
		discount: 0,
	},
	{
		id: 'g_19',
		image: process.env.PUBLIC_URL+'/images/g19.jpg',
		name: "CATACOMBS: THE BEGINNING",
		tag01: '캐주얼',
		tag02: '시뮬레이션',
		tag03: '액션',
		tag04: '슈팅',
		tag05: '탐험',
		tag06: 'best',
		date: '2023년 1월 28일',
		desc: "Catacombs: The Beginning - is an excellent 3D shooter where you have to survive in the catacombs overfull of various monsters.",
		price: 1100,
		discount: 0.4,
	},
	{
		id: 'g_20',
		image: process.env.PUBLIC_URL+'/images/g20.jpg',
		name: "ZERO SIEVERT",
		tag01: '생존',
		tag02: '포스트아포칼립스',
		tag03: '액션',
		tag04: '슈팅',
		tag05: '탐험',
		tag06: 'best',
		date: '2022년 11월 16일',
		desc: "ZERO Sievert는 알고리즘에 따라 생성된 황무지를 뒤지고 장비를 약탈하고 황폐해진 세계에 남아있는 것을 탐험하며 도전하는 긴장된 분위기의 탑다운 슈팅 게임입니다. 여러분에게 불리한 상황이 닥쳤을 때, 생존 그 이상의 일을 해내야 할 것입니다.",
		price: 21500,
		discount: 0.4,
	},
	{
		id: 'g_21',
		image: process.env.PUBLIC_URL+'/images/g21.jpg',
		name: "FROM SPACE",
		tag01: '액션',
		tag02: '협동',
		tag03: '멀티플레이어',
		tag04: '어드벤처',
		tag05: '온라인',
		tag06: 'best',
		date: '2022년 11월 4일',
		desc: "From Space는 싱글 플레이와 최대 네 명까지 협동 플레이가 가능한 액션 슈팅 게임입니다. 화려한 그래픽으로 그려진 포스트 아포칼립스 세계에서 최강의 무기를 들고 친구들과 함께 외계인이 들끓는 지구 해방에 도전하세요.",
		price: 17000,
		discount: 0.35,
	},
	{
		id: 'g_22',
		image: process.env.PUBLIC_URL+'/images/g22.jpg',
		name: "SCARLET TOWER",
		tag01: '뱀파이어',
		tag02: '액션 로그라이크',
		tag03: '판타지',
		tag04: '어드벤처',
		tag05: '픽셀 그래픽',
		tag06: 'best',
		date: '2022년 11월 1일',
		desc: "낮에는 사냥, 밤에는 사냥! Scarlet Tower는 탤런트 트리, 클래스, 패밀리어 등과 같은 로그라이크 및 RPG 요소가 포함된 고딕 공포 캐주얼 게임입니다!",
		price: 17000,
		discount: 0.35,
	},
	{
		id: 'g_23',
		image: process.env.PUBLIC_URL+'/images/g23.jpg',
		name: "IMMORTALS FENYX RISING",
		tag01: '액션',
		tag02: '어드벤처',
		tag03: 'RPG',
		tag04: '모험',
		tag05: '판타지',
		tag06: 'best',
		date: '2022년 12월 16일',
		desc: "Immortals Fenyx Rising에서 웅장한 신화 속 모험이 현실이 됩니다. 피닉스가 되어 그리스 신들을 구하기 위한 과업을 완수하세요.",
		price: 65000,
		discount: 0,
	},
	{
		id: 'g_24',
		image: process.env.PUBLIC_URL+'/images/g24.jpg',
		name: "지옥의 균열",
		tag01: 'RPG',
		tag02: '액션',
		tag03: '타워 디펜스',
		tag04: '모험',
		tag05: '판타지',
		tag06: 'best',
		date: '2023년 1월 17일',
		desc: "몰려드는 지옥의 괴물들을 격파하여 인류를 구원하라 다양한 능력을 가진 영웅들로 이루어진 막강한 군대로 방어 하십시오",
		price: 2300,
		discount: 0,
	},
	{
		id: 'g_25',
		image: process.env.PUBLIC_URL+'/images/g25.jpg',
		name: "MARTIAL FIRE",
		tag01: '어드벤처',
		tag02: '액션',
		tag03: 'RPG',
		tag04: '모험',
		tag05: '판타지',
		tag06: 'new',
		date: '2023년 1월 17일',
		desc: "Martial Fire is a classic 2D adventure game. Explore dungeons, ancient forests and deadly wastelands; fight enemies and solve riddles!",
		price: 27000,
		discount: 0,
	},
  {
		id: 'g_26',
		image: process.env.PUBLIC_URL+'/images/g26.jpg',
		name: "ELDER TRIAL：PROLOGUE",
		tag01: '로그라이트',
		tag02: '액션',
		tag03: '판타지',
		tag04: '인디',
		tag05: 'STEP',
		tag06: 'new',
		date: '2023년 1월 25일',
		desc: "Elder Trial is a Rougelike ARPG game with Customizable Abilities,each Ability has a variety of Customizable Enhancement Options,and it can also Super Evolution!The game also has a large number of Weapons,Amulets,Random Events…You can have fun every time you play the game!",
		price: 0,
		discount: 0,
	},
  {
		id: 'g_27',
		image: process.env.PUBLIC_URL+'/images/g27.jpg',
		name: "HELL SLAYER",
		tag01: '로그라이트',
		tag02: '액션',
		tag03: '로그라이크',
		tag04: '인디',
		tag05: '슈팅',
		tag06: 'new',
		date: '2023년 1월 27일',
		desc: "Clear your way down to hell and bring punishment to the one responsible, Lucifer, fallen angel and king of sins. Face unending hordes of demons, optimize and perfect your build.",
		price: 3400,
		discount: 0,
	},
  {
		id: 'g_28',
		image: process.env.PUBLIC_URL+'/images/g28.jpg',
		name: "IN THE GYM (MEMES HORROR GAME)HELL SLAYER",
		tag01: '인디',
		tag02: '밈',
		tag03: '액션',
		tag04: '인디',
		tag05: '코미디',
		tag06: 'best',
		date: '2023년 1월 28일',
		desc: "Emotional horror about survival in a gym.",
		price: 1100,
		discount: 0.4,
	},
  {
		id: 'g_29',
		image: process.env.PUBLIC_URL+'/images/g29.jpg',
		name: "NEW WITCH IN TOWN",
		tag01: '캐주얼',
		tag02: 'RPG',
		tag03: '액션',
		tag04: '인디',
		tag05: '어드벤처',
		tag06: 'best',
		date: '2023년 1월 26일',
		desc: "Make friends, cast spells, and uncover secrets in your magical small town! Will you preserve the forest or let the town grow?",
		price: 9900,
		discount: 0.34,
	},
  {
		id: 'g_30',
		image: process.env.PUBLIC_URL+'/images/g30.jpg',
		name: "FINNISH ARMY SIMULATOR",
		tag01: '군사',
		tag02: '코미디',
		tag03: '다이내믹',
		tag04: 'RPG',
		tag05: '패러디',
		tag06: 'new',
		date: '2023년 1월 14일',
		desc: "Military service, just like you remember it! Or if you don’t, you’ll feel like you do.",
		price: 32000,
		discount: 0,
	},
  {
		id: 'g_31',
		image: process.env.PUBLIC_URL+'/images/g31.jpg',
		name: "BING IN WONDERLAND",
		tag01: '액션',
		tag02: '로그라이크',
		tag03: '어드벤처',
		tag04: 'RPG',
		tag05: '패러디',
		tag06: 'best',
		date: '2023년 1월 13일',
		desc: "A Roguelite monster killing satisfaction galore without any exploration elements.",
		price: 9900,
		discount: 0,
	},
  {
		id: 'g_32',
		image: process.env.PUBLIC_URL+'/images/g32.jpg',
		name: "WARPLANES: BATTLES OVER PACIFIC",
		tag01: '시뮬레이션',
		tag02: '액션',
    tag03: '비행',
		tag04: 'VR',
		tag05: '아케이드',
		tag06: 'best',
		date: '2023년 1월 27일',
		desc: "Warplanes: Battles over Pacific opens the next chapter in aviation history. Become a World War II pilot and take part in the campaign against the Empire of Japan. The sequel to the hit Warplanes: WW1 Fighters, takes dogfight to a new level.",
		price: 20500,
		discount: 0,
	},
  {
		id: 'g_33',
		image: process.env.PUBLIC_URL+'/images/g33.jpg',
		name: "BREAKERS COLLECTION",
		tag01: '시뮬레이션',
		tag02: '2D',
    tag03: '격투',
		tag04: 'PvP',
		tag05: '아케이드',
		tag06: 'best',
		date: '2023년 1월 12일',
		desc: "Breakers Collection features both of the original games (Breakers and Breakers Revenge) and a brand new content for the cult-classic among the fans of Fighting Games, that was released in 1996 for the Neogeo and Arcades.",
		price: 20500,
		discount: 0,
	},
  {
		id: 'g_34',
		image: process.env.PUBLIC_URL+'/images/g34.jpg',
		name: "트리 오브 세이비어",
		tag01: 'RPG',
		tag02: '판타지',
    tag03: 'MMORPG',
		tag04: '플레이어',
		tag05: '액션',
		tag06: 'best',
		date: '2023년 1월 12일',
		desc: "거대한 나무가 지상에 등장한 이후, 인간들을 보살펴주던 여신들은 종적을 감추고, 인간들은 갑작스레 나타난 몬스터와 맞닥뜨리게 됩니다.",
		price: 20500,
		discount: 0,
	},
  {
		id: 'g_35',
		image: process.env.PUBLIC_URL+'/images/g35.jpg',
		name: "AFTER WAVE: DOWNFALL",
		tag01: '액션',
		tag02: '레이싱',
    tag03: '외계인',
		tag04: '3D',
		tag05: '아케이드',
		tag06: 'new',
		date: '2023년 1월 20일',
		desc: "Arcade shooter where the player battles against monsters, completes various missions with a cool battleship. Deathrix invaded the world and released a mysterious meteorite causing a great flood. Players can upgrade their ships for better.",
		price: 11000,
		discount: 0,
	},
  {
		id: 'g_36',
		image: process.env.PUBLIC_URL+'/images/g36.jpg',
		name: "ZOMBIES ROCKET BOOM BOOM",
		tag01: '액션',
		tag02: '캐주얼',
    tag03: '시뮬레이션',
		tag04: 'RPG',
		tag05: '아케이드',
		tag06: 'new',
		date: '2023년 1월 12일',
		desc: "Welcome in this casual game of Zombies Rocket Boom Boom.",
		price: 4500,
		discount: 0,
	},
  {
		id: 'g_37',
		image: process.env.PUBLIC_URL+'/images/g37.jpg',
		name: "FUKTOPIA 5",
		tag01: '액션',
		tag02: '어드벤처',
    tag03: '격투',
		tag04: '로그라이크',
		tag05: '아케이드',
		tag06: 'new',
		date: '2023년 1월 30일',
		desc: "FukTopia 5 is a frantic post apocalyptic Top Down game.",
		price: 26000,
		discount: 0.4,
	},
  {
		id: 'g_38',
		image: process.env.PUBLIC_URL+'/images/g38.jpg',
		name: "SPACE ESCAPER",
		tag01: '슈팅',
		tag02: '비행',
    tag03: '탄막',
		tag04: '우주',
		tag05: '아케이드',
		tag06: 'new',
		date: '2023년 1월 31일',
		desc: "It's a pixel art space shooter that has some other ways to help defeat enemies besides just shooting/bombing them directly. Different abilities to help you avoid damage or defeat enemies. You also can upgrade your aircraft to defeat",
		price: 1100,
		discount: 0.1,
	},
  {
		id: 'g_39',
		image: process.env.PUBLIC_URL+'/images/g39.jpg',
		name: "ENDLESS NESLA",
		tag01: '액션',
		tag02: '플랫폼',
    tag03: '러너',
		tag04: '우주',
		tag05: '아케이드',
		tag06: 'best',
		date: '2023년 1월 31일',
		desc: "Endless Nesla is a demanding infinite runner game with dynamic movement mechanics and immersive graphics. Escape Nesla, and challenge other players on the Leaderboards !",
		price: 4500,
		discount: 0,
	},
  {
		id: 'g_40',
		image: process.env.PUBLIC_URL+'/images/g40.jpg',
		name: "TEAMPUNK",
		tag01: '액션',
		tag02: '스틱',
    tag03: '슈팅',
		tag04: '스팀펑크',
		tag05: '아케이드',
		tag06: 'new',
		date: '2023년 1월 20일',
		desc: "A steampunk twinstick shooter where you and your team need to work together to protect the Convoy.",
		price: 0,
		discount: 0,
	},
  {
		id: 'g_41',
		image: process.env.PUBLIC_URL+'/images/g41.jpg',
		name: "EASY GAME",
		tag01: '액션',
		tag02: '캐주얼',
    tag03: '2D',
		tag04: '어드벤처',
		tag05: '아케이드',
		tag06: 'best',
		date: '2023년 1월 30일',
		desc: "입문하기 쉬운 정통파 2D 플랫폼 게임입니다. 플랫폼 게임을 처음 하시는 분들에게 적절한 난이도로 장애물을 피해 보스를 공략하세요.",
		price: 3300,
		discount: 0,
	},
  {
		id: 'g_42',
		image: process.env.PUBLIC_URL+'/images/g42.jpg',
		name: "NORDIC ASHES: SURVIVORS OF RAGNAROK",
		tag01: '액션',
		tag02: '로그라이크',
    tag03: '아레나',
		tag04: '슈팅',
		tag05: '캐주얼',
		tag06: 'new',
		date: '2022년 12월 16일',
		desc: "Nordic Ashes is a Norse inspired action-roguelite enemy hell, where you’ll have to survive hordes of creatures. Unlock new weapons and abilities as you battle through different realms. Design the most broken build and slay your enemies before",
		price: 5600,
		discount: 0,
	},
  {
		id: 'g_43',
		image: process.env.PUBLIC_URL+'/images/g43.jpg',
		name: "KITCHEN CHAOS",
		tag01: '액션',
		tag02: '전략',
    tag03: '3D',
		tag04: '다채로운',
		tag05: '캐주얼',
		tag06: 'best',
		date: '2022년 12월 16일',
		desc: "This is a learning project, learn how to build this game! - The customers are hungry, it's up to you to fill them up with all kinds of interesting interactions!",
		price: 0,
		discount: 0,
	},
  {
		id: 'g_44',
		image: process.env.PUBLIC_URL+'/images/g44.jpg',
		name: "STEWART THE FOX",
		tag01: '액션',
		tag02: '어드벤처',
    tag03: '3D',
		tag04: '큐트',
		tag05: '캐주얼',
		tag06: 'new',
		date: '2023년 1월 20일',
		desc: "Join Stewart the Fox on an epic adventure through four challenging levels filled with obstacles, enemies, and two boss battles. As you collect hidden items to help Stewart emerge victorious in this action-packed platformer game.",
		price: 0,
		discount: 0,
	},
  {
		id: 'g_45',
		image: process.env.PUBLIC_URL+'/images/g45.jpg',
		name: "THE ROCKET JUMPER",
		tag01: '액션',
		tag02: '플랫폼',
    tag03: '1인칭',
		tag04: '슈팅',
		tag05: '캐주얼',
		tag06: 'best',
		date: '2023년 1월 28일',
		desc: "The Rocket Jumper is a 3D platformer that puts a twist on traditional gameplay by incorporating rocket jumping as the main element.",
		price: 6700,
		discount: 0,
  },
  {
		id: 'g_46',
		image: process.env.PUBLIC_URL+'/images/g46.jpg',
		name: "GORILLA TAG",
		tag01: '심리적공포',
		tag02: 'VR',
    tag03: '멀티플레이어',
		tag04: '파쿠르',
		tag05: '캐주얼',
		tag06: 'new',
		date: '2023년 1월 2일',
		desc: "Run, jump, and climb using only your hands. Play tag or infection with people online. Run away from the infected players, or outmaneuver the survivors to catch them. Embrace your inner ape.",
		price: 21500,
		discount: 0,
  },
  {
		id: 'g_47',
		image: process.env.PUBLIC_URL+'/images/g47.jpg',
		name: "PIEN-HING- & PAON PLUS",
		tag01: '액션',
		tag02: '어드벤처',
    tag03: '3D',
		tag04: '1인칭',
		tag05: '캐주얼',
		tag06: 'best',
		date: '2022년 12월 6일',
		desc: "수수께끼의 몬스터 'PIEN'과 'PAON'으로부터 도망치세요! 팝하고 귀여운 공포 게임!",
		price: 4500,
		discount: 0,
  },
  {
		id: 'g_48',
		image: process.env.PUBLIC_URL+'/images/g48.jpg',
		name: "LOST EGG 3: THE FINAL",
		tag01: '플랫폼',
		tag02: '어드벤처',
    tag03: '3D',
		tag04: '액션',
		tag05: '캐주얼',
		tag06: 'best',
		date: '2023년 1월 2일',
		desc: "The egg's great adventure, the final chapter. That fragile but brave egg has returned with even more new powers, but this time its adventure is over.",
		price: 3400,
		discount: 0,
  },
  {
		id: 'g_49',
		image: process.env.PUBLIC_URL+'/images/g49.jpg',
		name: "INTO THE FLAMES",
		tag01: '시뮬레이션',
		tag02: '액션',
    tag03: '인디',
		tag04: '멀티플레이어',
		tag05: '캐주얼',
		tag06: 'new',
		date: '2023년 1월 11일',
		desc: "Into The Flames is a Solo/Co-op firefighting game that focuses on the intensity of being a real life firefighter. Drive emergency vehicles, bust down doors, fight raging fires, and do whatever it takes to bring the chaotic scene under control!",
		price: 20500,
		discount: 0,
  },
  {
		id: 'g_50',
		image: process.env.PUBLIC_URL+'/images/g50.jpg',
		name: "AKARI: SCHOOL TRIP",
		tag01: '어드벤처',
		tag02: '액션',
    tag03: '탐험',
		tag04: '3인칭',
		tag05: '캐주얼',
		tag06: 'new',
		date: '2023년 1월 26일',
		desc: "Akari: School Trip is an immersive, action-packed adventure game based on a popular Japanese manga. As the player guides Akari, a courageous school girl, through a mysterious and dangerous world.",
		price: 21500,
		discount: 0.1,
  },
  {
		id: 'g_51',
		image: process.env.PUBLIC_URL+'/images/g51.jpg',
		name: "NEPTUNIA: SISTERS VS SISTERS",
		tag01: 'RPG',
		tag02: '액션',
    tag03: '애니메이션',
		tag04: 'JRPG',
		tag05: '파이터',
		tag06: 'new',
		date: '2023년 1월 26일',
		desc: "With Gamindustri on the brink of destruction, Nepgear and the Candidates must band together and restore order!",
		price: 51000,
		discount: 0.1,
  },
  {
		id: 'g_52',
		image: process.env.PUBLIC_URL+'/images/g52.jpg',
		name: "PUNCH A BUNCH",
		tag01: '복싱',
		tag02: '격투',
    tag03: '물리',
		tag04: '인디',
		tag05: '파이터',
		tag06: 'best',
		date: '2023년 1월 21일',
		desc: "A challenging boxing game with an emphasis on player skill that takes time and practice to master. Fight your way to the top through 3 different championships each featuring unique opponents.",
		price: 16500,
		discount: 0,
  },
  {
		id: 'g_53',
		image: process.env.PUBLIC_URL+'/images/g53.jpg',
		name: "EVIL WEST",
		tag01: '액션',
		tag02: '어드벤처',
    tag03: '웨스턴',
		tag04: '슈팅',
		tag05: '파이터',
		tag06: 'best',
		date: '2022년 11월 22일',
		desc: "어둠의 위협이 옛 서부를 잠식해갑니다. 혼자 또는 협동 모드에서 피에 굶주린 괴물들과 멋지고 화끈하게 싸우십시오. 번개가 깃든 건틀렛으로 뱀파이어 군대를 쳐부수고 거친 서부의 슈퍼히어로가 되십시오.",
		price: 53800,
		discount: 0.25,
  },
  {
		id: 'g_54',
		image: process.env.PUBLIC_URL+'/images/g54.jpg',
		name: "FRAYMAKERS",
		tag01: '인디',
		tag02: '격투',
    tag03: '멀티플레이어',
		tag04: '워크숍',
		tag05: '파이터',
		tag06: 'new',
		date: '2023년 1월 19일',
		desc: "Fraymakers is the ultimate customizable platform fighting game, featuring a cast of some of indie gaming's biggest icons. Duke it out with up to 4 players and call on assists to help out in the heat of battle.",
		price: 20500,
		discount: 0,
  },
  {
		id: 'g_55',
		image: process.env.PUBLIC_URL+'/images/g55.jpg',
		name: "CHECKMATE KINGS",
		tag01: '탄막',
		tag02: '슈팅',
    tag03: '멀티플레이어',
		tag04: '2D',
		tag05: '파이터',
		tag06: 'best',
		date: '2023년 1월 31일',
		desc: "Checkmate Kings is a high-paced chess-like multiplayer bullet hell 👑 Shoot at your opponent, summon chess pieces, dash around the arena and crush the enemy king!",
		price: 11000,
		discount: 0.1,
  },
  {
		id: 'g_56',
		image: process.env.PUBLIC_URL+'/images/g56.jpg',
		name: "DIVINE KNOCKOUT (DKO)",
		tag01: '액션',
		tag02: '3D',
    tag03: '멀티플레이어',
		tag04: '판타지',
		tag05: '파이터',
		tag06: 'new',
		date: '2022년 12월 6일',
		desc: "KO the gods in the world’s only 3rd-person platform fighter! Become a small-but-mighty god of myth, brawl in all three dimensions, and knock your friends off the map to reign supreme.",
		price: 11000,
		discount: 0,
  },
  {
		id: 'g_57',
		image: process.env.PUBLIC_URL+'/images/g57.jpg',
		name: "BRAVERY AND GREED",
		tag01: '멀티플레이어',
		tag02: '로그라이트',
    tag03: '슬래시',
		tag04: '액션',
		tag05: '파이터',
		tag06: 'best',
		date: '2022년 11월 16일',
		desc: "Bravery and Greed는 비뎀업, 로그라이트, 던전 브롤러 장르로 최대 4명까지 플레이할 수 있습니다.",
		price: 21500,
		discount: 0,
  },
  {
		id: 'g_58',
		image: process.env.PUBLIC_URL+'/images/g58.jpg',
		name: "SCOTT PILGRIM VS. THE WORLD™: THE GAME – COMPLETE EDITION",
		tag01: '액션',
		tag02: '어드벤처',
    tag03: '온라인',
		tag04: '액션',
		tag05: '파이터',
    tag06: 'new',
		date: '2023년 1월 19일',
		desc: "유명 그래픽 노블 시리즈이자 영화인 Scott Pilgrim Vs. The World가 클래식한 2D 아케이드 스타일의 격투 게임으로 재탄생합니다!",
		price: 16500,
		discount: 0,
  },
  {
		id: 'g_59',
		image: process.env.PUBLIC_URL+'/images/g59.jpg',
		name: "EX_HOLICS.EXE",
		tag01: '액션',
		tag02: '3D',
    tag03: '격투',
		tag04: '로그라이크',
		tag05: '파이터',
    tag06: 'new',
		date: '2023년 1월 27일',
		desc: "Delete all enemy players in abandoned cyber space! You have gatling, beam canon, misslies and more various weapons.",
		price: 14500,
		discount: 0.4,
  },
  {
		id: 'g_60',
		image: process.env.PUBLIC_URL+'/images/g60.jpg',
		name: "AGENT IN DEPTH",
		tag01: '닌자',
		tag02: '초고난도',
    tag03: '픽셀',
		tag04: '액션',
		tag05: '파이터',
		tag06: 'new',
		date: '2023년 1월 21일',
		desc: "에이전트 인 디피티는 빠른 속도의 액션과 즉각적인 죽음의 전투를 특징으로 하는 대담한 액션 플랫폼입니다. 여러분은 적들을 폭파시키기 위해 너희들의 카타나로 달리고, 뛰하고, 조준하고, 총알의 방향을 바꿀 것입니다.",
		price: 3400,
		discount: 0,
  },
  {
		id: 'g_61',
		image: process.env.PUBLIC_URL+'/images/g61.jpg',
		name: "TRUCK SIMULATOR ULTIMATE 3D",
		tag01: '액션',
		tag02: '레이싱',
    tag03: '시뮬레이션',
		tag04: '인디',
		tag05: '오픈 월드',
		tag06: 'best',
		date: '2023년 1월 30일',
		desc: "도시에서 좋은 트럭 운전사로 모든 트럭 게임 임무를 완수하십시오.",
		price: 1100,
		discount: 0.1,
  },
  {
		id: 'g_62',
		image: process.env.PUBLIC_URL+'/images/g62.jpg',
		name: "소닉 프론티어",
		tag01: '어드벤처',
		tag02: '웅장한',
    tag03: '사운드트랙',
		tag04: '액션',
		tag05: '오픈 월드',
		tag06: 'best',
		date: '2022년 11월 8일',
		desc: "『소닉 프론티어』는 소닉 특유의 초음속 액션으로 광대한 섬을 자유롭게 누비는 종횡무진 새로운 경지의 액션 어드벤처입니다.",
		price: 49800,
		discount: 0,
  },
  {
		id: 'g_63',
		image: process.env.PUBLIC_URL+'/images/g63.jpg',
		name: "트라하 글로벌",
		tag01: '전투',
		tag02: 'MMORPG',
    tag03: '협동',
		tag04: '액션',
		tag05: '오픈 월드',
		tag06: 'new',
		date: '2022년 11월 2일',
		desc: "트라하 글로벌은 나이아드 및 불칸 양대 진영의 대립을 바탕으로 하는 RvR MMORPG입니다. 트라하는 자유로운 클래스 변경 시스템을 바탕으로 여러 직업의 역할을 수행할 수 있으며 스킬 조합 및 스킬 트리거를 통해 전투에서 다양한 변수를 만들어낼 수 있습니다.",
		price: 0,
		discount: 0,
  },
  {
		id: 'g_64',
		image: process.env.PUBLIC_URL+'/images/g64.jpg',
		name: "BUS SIMULATOR: CAR DRIVING",
		tag01: '액션',
		tag02: '시뮬레이션',
    tag03: '인디',
		tag04: '자동차',
		tag05: '오픈 월드',
		tag06: 'best',
		date: '2023년 1월 25일',
		desc: "이 버스 게임 시뮬레이터에서 훌륭한 대중 버스 운전사가 되어야 합니다.",
		price: 1100,
		discount: 0.15,
  },
  {
		id: 'g_65',
		image: process.env.PUBLIC_URL+'/images/g65.jpg',
		name: "QUEST TOGETHER",
		tag01: '액션',
		tag02: 'RPG',
    tag03: '인디',
		tag04: '어드벤처',
		tag05: '오픈 월드',
		tag06: 'new',
		date: '2022년 12월 24일',
		desc: "Take up your sword and shield and go on a quest with your friends!",
		price: 16500,
		discount: 0,
  },
  {
		id: 'g_66',
		image: process.env.PUBLIC_URL+'/images/g66.jpg',
		name: "OSIRIS: NEW DAWN",
		tag01: '생존',
		tag02: '제작',
    tag03: '공포',
		tag04: '우주',
		tag05: '오픈 월드',
		tag06: 'best',
		date: '2023년 1월 19일',
		desc: "Osiris: New Dawn is an unforgiving near future space survival game with a cinematic feel and elements of horror.",
		price: 21500,
		discount: 0,
  },
  {
		id: 'g_67',
		image: process.env.PUBLIC_URL+'/images/g67.jpg',
		name: "171",
		tag01: '액션',
		tag02: '인디',
    tag03: '고어',
		tag04: '범죄',
		tag05: '오픈 월드',
		tag06: 'new',
		date: '2022년 11월 17일',
		desc: "171 is an open world action adventure game with a Brazilian inspired ambience.",
		price: 31000,
		discount: 0,
  },
  {
		id: 'g_68',
		image: process.env.PUBLIC_URL+'/images/g68.jpg',
		name: "WILD TERRA 2: NEW LANDS",
		tag01: '생존',
		tag02: '제작',
    tag03: '샌드박스',
		tag04: 'MMORPG',
		tag05: '오픈 월드',
		tag06: 'best',
		date: '2022년 11월 11일',
		desc: "MMORPG full of details that create a unique immersion and the spirit of adventure! Play your role in the life-filled medieval world controlled by players.",
		price: 39900,
		discount: 0,
  },
  {
		id: 'g_69',
		image: process.env.PUBLIC_URL+'/images/g69.jpg',
		name: "INTERSTELLAR PILOT 2",
		tag01: '액션',
		tag02: '시뮬레이션',
    tag03: '우주',
		tag04: '전략',
		tag05: '오픈 월드',
		tag06: 'new',
		date: '2023년 1월 2일',
		desc: "The hit mobile game Interstellar Pilot 2 has come to Steam. Join the TEF forces heading to the Gatopean sector to find a new home for mankind. Play how you like in this open world space-sim developed by Pixelfactor.",
		price: 4500,
		discount: 0,
  },
  {
		id: 'g_70',
		image: process.env.PUBLIC_URL+'/images/g70.jpg',
		name: "ARCANE VALE",
		tag01: '액션',
		tag02: '어드벤처',
    tag03: 'RPG',
		tag04: '모험',
		tag05: '오픈 월드',
		tag06: 'best',
		date: '2023년 1월 2일',
		desc: "Arcane Vale is an action packed open-world RPG. Embark on an adventure to discover a long-lost treasure in a vast and dangerous world.",
		price: 8500,
		discount: 0,
  },
  {
		id: 'g_71',
		image: process.env.PUBLIC_URL+'/images/g71.jpg',
		name: "SKUL: THE HERO SLAYER",
		tag01: '인디',
		tag02: '액션',
    tag03: '로그라이크',
		tag04: '픽셀 그래픽',
		tag05: '플랫폼',
		tag06: 'new',
		date: '2021년 1월 21일',
		desc: "Skul: The Hero Slayer는 2D 로그라이트 액션 플랫포머 게임입니다. 마왕성 경비를 맡고있는 꼬마 스켈레톤 '스컬'은 인간들에게 붙잡혀간 마왕을 구하기 위해 용사와 모험가 그리고 제국군에 홀로 맞서 싸우기 시작합니다.",
		price: 20500,
		discount: 0,
  },
  {
		id: 'g_72',
		image: process.env.PUBLIC_URL+'/images/g72.jpg',
		name: "ORI AND THE WILL OF THE WISPS",
		tag01: '메트로',
		tag02: '웅장한',
    tag03: '사운드트랙',
		tag04: '액션',
		tag05: '플랫폼',
		date: '2020년 3월 11일',
		desc: "거대하고 이국적인 세계에서 새로운 여정을 시작하세요. 오리의 운명을 밝혀내면서 강력한 적들과 어려운 퍼즐을 만나게 될 것입니다.",
		price: 29900,
		discount: 0.67,
  },
  {
		id: 'g_73',
		image: process.env.PUBLIC_URL+'/images/g73.jpg',
		name: "PICO PARK",
		tag01: '멀티플레이어',
		tag02: '온라인',
    tag03: '협동',
		tag04: '퍼즐',
		tag05: '플랫폼',
		date: '2021년 5월 7일',
		desc: "PICO PARK is a cooperative local/online multiplay action puzzle game for 2-8 players.",
		price: 5500,
		discount: 0.67,
  },
  {
		id: 'g_74',
		image: process.env.PUBLIC_URL+'/images/g74.jpg',
		name: "CUPHEAD",
		tag01: '고난이도',
		tag02: '만화',
    tag03: '협동',
		tag04: '사운드트랙',
		tag05: '플랫폼',
		tag06: 'best',
		date: '2017년 9월 29일',
		desc: "Cuphead는 보스전에 무게를 둔 정통파 횡 스크롤 액션 게임입니다. 1930년대 카툰풍 애니메이션에서 영감을 얻은 본 작품의 그래픽과 사운드 등은 수작업 셀 애니메이션, 수채화 배경, 독자적인 재즈 레코딩을 비롯한 당시 기술을 그대로 활용하여 꼼꼼하게 제작되었습니다.",
		price: 21000,
		discount: 0,
  },
  {
		id: 'g_75',
		image: process.env.PUBLIC_URL+'/images/g75.jpg',
		name: "프런티어 헌터： 엘사의 운명의 바퀴",
		tag01: '메트로',
		tag02: '탐험',
    tag03: '애니메이션',
		tag04: 'RPG',
		tag05: '플랫폼',
		tag06: 'new',
		date: '2022년 12월 15일',
		desc: "제국의 우주함 발명으로 공중에 떠 있는 여러 대륙과 섬을 오갈 수 있게 되면서 영토가 급속하게 확장되었습니다. 제국 정부의 세력이 닿지 않는 국경 지역에서, 최고의 헌터 엘사가 탐색 팀을 이끄며 새로운 대륙을 도착했습니다. 과연 그들의 운명은?",
		price: 21500,
		discount: 0.2,
  },
  {
		id: 'g_76',
		image: process.env.PUBLIC_URL+'/images/g76.jpg',
		name: "NATURAL SPIRIT",
		tag01: '액션',
		tag02: '어드벤처',
    tag03: '탐험',
		tag04: '3D',
		tag05: '플랫폼',
		tag06: 'best',
		date: '2023년 1월 30일',
		desc: "Natural Spirit is a third-person adventure game where you will play as the shiba Yukito, to help the spirit Aura to save the tree of life from a certain death that would doom us all.",
		price: 10500,
		discount: 0,
  },
  {
		id: 'g_77',
		image: process.env.PUBLIC_URL+'/images/g77.jpg',
		name: "SENTINEL",
		tag01: '액션',
		tag02: '어드벤처',
    tag03: '만화',
		tag04: '2D',
		tag05: '플랫폼',
		tag06: 'new',
		date: '2023년 1월 30일',
		desc: "Explore, fight, and grow stronger as you progress through this 2D Metroidvania-style platformer. Can you uncover the secrets that hide on our moon?",
		price: 0,
		discount: 0,
  },
  {
		id: 'g_78',
		image: process.env.PUBLIC_URL+'/images/g78.jpg',
		name: "PALETTE SWAP",
		tag01: '액션',
		tag02: '어드벤처',
    tag03: '만화',
		tag04: '퍼즐',
		tag05: '플랫폼',
		tag06: 'new',
		date: '2023년 1월 21일',
		desc: "A monochrome action platformer where the palette changes the environment around you.",
		price: 5600,
		discount: 0,
  },
  {
		id: 'g_79',
		image: process.env.PUBLIC_URL+'/images/g79.jpg',
		name: "AMABILLY",
		tag01: '2D',
		tag02: '모험',
    tag03: '액션',
		tag04: '여주인공',
		tag05: '플랫폼',
		tag06: 'new',
		date: '2023년 1월 31일',
		desc: "Amabilly is a lovely girl who loves rock 'n' roll, and this story is about her greatest adventure! With her favorite guitar as a weapon, she faces strange creatures and even the greatest of the challenges! It's time to Rock!",
		price: 5600,
		discount: 0.2,
  },
  {
		id: 'g_80',
		image: process.env.PUBLIC_URL+'/images/g80.jpg',
		name: "AXIOM",
		tag01: '3D',
		tag02: '파쿠르',
    tag03: '액션',
		tag04: '소설',
		tag05: '플랫폼',
		tag06: 'best',
		date: '2023년 1월 1일',
		desc: "In a cyberpunk world where giant corporations take advantage of their power, only those with the ability to enter the human mind can stop corruption at its source.",
		price: 0,
		discount: 0,
  },
  {
		id: 'g_81',
		image: process.env.PUBLIC_URL+'/images/g81.jpg',
		name: "WORLD WAR 3",
		tag01: '1인칭',
		tag02: '전쟁',
    tag03: '멀티플레이어',
		tag04: '군사',
		tag05: '슈팅',
		date: '2023년 1월 1일',
		desc: "World War 3 is a Free-to-play tactical online multiplayer FPS where the world is your battleground. Outgun the enemy in thrilling, team-based skirmishes with a huge arsenal of weapons, vehicles, gadgets, and drones at your disposal.",
		price: 0,
		discount: 0,
  },
  {
		id: 'g_82',
		image: process.env.PUBLIC_URL+'/images/g82.jpg',
		name: "RISING FRONT",
		tag01: '액션',
		tag02: '세계 대전',
    tag03: '싱글 플레이어',
		tag04: '전쟁',
		tag05: '슈팅',
    tag06: 'new',
		date: '2023년 1월 15일',
		desc: "A FPS WW1 battle simulator with a focus on rag-doll physics, intelligent AI, massive battles, procedural AI cover system, real-time building system and FPS combat!",
		price: 16500,
		discount: 0,
  },
  {
		id: 'g_83',
		image: process.env.PUBLIC_URL+'/images/g83.jpg',
		name: "PARAGON: THE OVERPRIME",
		tag01: '공상과학',
		tag02: '시네마틱',
    tag03: '3인칭',
		tag04: '멀티플레이어',
		tag05: '슈팅',
		date: '2023년 1월 15일',
		desc: "파라곤: 디 오버프라임은 팀을 기반으로 플레이하는 무료 TPS Action MOBA 게임입니다. 개성 넘치는 스킬을 보유한 다양한 영웅들 중 하나가 되어 전장에 참여하세요.",
		price: 0,
		discount: 0,
  },
  {
		id: 'g_84',
		image: process.env.PUBLIC_URL+'/images/g84.jpg',
		name: "PORTAL DUNGEON",
		tag01: '온라인',
		tag02: '협동',
    tag03: '액션',
		tag04: '로그라이크',
		tag05: '슈팅',
		date: '2022년 12월 15일',
		desc: "In “Portal Dungeon”, in this multiplayer Roguelite adventure game with random elements, as an adventurer, you and your friends will bravely find the last portal in this portal world, defeat powerful enemies and save the world.",
		price: 14500,
		discount: 0,
  },
  {
		id: 'g_85',
		image: process.env.PUBLIC_URL+'/images/g85.jpg',
		name: "PREDECESSOR",
		tag01: '전략',
		tag02: '3인칭',
    tag03: '멀티플레이어',
		tag04: '전투',
		tag05: '슈팅',
		date: '2022년 12월 1일',
		desc: "Predecessor is a fast-paced action game that combines MOBA and FPS gameplay putting you at the heart of the fight with strategic choice, third-person control and immersive action.",
		price: 22100,
		discount: 0,
  },
  {
		id: 'g_86',
		image: process.env.PUBLIC_URL+'/images/g86.jpg',
		name: "CRYSIS 2 REMASTERED",
		tag01: '액션',
		tag02: '1인칭',
    tag03: '샌드박스',
		tag04: '히어로',
		tag05: '슈팅',
		tag06: 'best',
		date: '2022년 11월 17일',
		desc: "Relive the legendary single-player campaign from the classic first-person shooter, Crysis 2, optimized for today's hardware in Crysis 2 Remastered.",
		price: 31000,
		discount: 0.4,
  },
  {
		id: 'g_87',
		image: process.env.PUBLIC_URL+'/images/g87.jpg',
		name: "EARTH'S SHADOW",
		tag01: '액션',
		tag02: 'RPG',
    tag03: '슈팅',
		tag04: '던전',
		tag05: '슈팅',
		tag06: 'new',
		date: '2023년 2월 1일',
		desc: "Earth's Shadow is a third person action Sci-Fi dungeon crawler set in the year 3081 on planet Sumbra.",
		price: 31000,
		discount: 0.4,
  },
  {
		id: 'g_88',
		image: process.env.PUBLIC_URL+'/images/g88.jpg',
		name: "DZOMBZ",
		tag01: '생존',
		tag02: '공포',
    tag03: '인디',
		tag04: '싱글 플레이어',
		tag05: '슈팅',
    tag06: 'new',
		date: '2023년 1월 30일',
		desc: "Survive or die ! Experience survival horror full of puzzles while escaping between the streets of Algeria after zombies invasion.",
		price: 14500,
		discount: 0.24,
  },
  {
		id: 'g_89',
		image: process.env.PUBLIC_URL+'/images/g89.jpg',
		name: "STALCRAFT",
		tag01: '1인칭',
		tag02: '액션',
    tag03: 'MMORPG',
		tag04: '어드벤처',
		tag05: '슈팅',
		tag06: 'best',
		date: '2023년 1월 30일',
		desc: "STALCRAFT is a dynamic MMOFPS with survival horror elements, set in the open world of the Chernobyl Exclusion Zone.",
		price: 0,
		discount: 0,
  },
  {
		id: 'g_90',
		image: process.env.PUBLIC_URL+'/images/g90.jpg',
		name: "HOOD WARFARE",
		tag01: '1인칭',
		tag02: '액션',
    tag03: '멀티플레이어',
		tag04: '범죄',
		tag05: '슈팅',
		tag06: 'new',
		date: '2023년 1월 26일',
		desc: "Welcome to Detroit. Gang violence has become an epidemic, forcing all civilians and police to leave the city. All that remains are soldiers of the Bloods and Crips.",
		price: 5600,
		discount: 0,
  },
  {
		id: 'g_91',
		image: process.env.PUBLIC_URL+'/images/g91.jpg',
		name: "MELATONIN",
		tag01: '인디',
		tag02: '리듬',
    tag03: '액션',
		tag04: '일러스트',
		tag05: '컨트롤러',
		tag06: 'best',
		date: '2022년 12월 16일',
		desc: "Melatonin is a rhythm game about dreams and reality merging together. It uses animations and sound cues to keep you on beat without any intimidating overlays or interfaces.",
		price: 16500,
		discount: 0,
  },
  {
		id: 'g_92',
		image: process.env.PUBLIC_URL+'/images/g92.jpg',
		name: "SHIP OF FOOLS",
		tag01: '협동',
		tag02: '로그라이트',
    tag03: '액션',
		tag04: '멀티플레이어',
		tag05: '컨트롤러',
		tag06: 'new',
		date: '2022년 11월 23일',
		desc: "Ship of Fools는 바다에서 항해하며 즐기는 로그라이트 게임입니다. 폭풍우가 몰아치는 열도의 바다를 항해하며, 대포를 조종하고 바다 괴물을 상대해보세요. 여러분은 재앙을 막아설 정도의 용감함을 가지고 계신가요?",
		price: 17400,
		discount: 0,
  },
  {
		id: 'g_93',
		image: process.env.PUBLIC_URL+'/images/g93.jpg',
		name: "THE MADNESS OF DEATH",
		tag01: '액션',
		tag02: '어드벤처',
    tag03: '시뮬레이션',
		tag04: '탐험',
		tag05: '컨트롤러',
		tag06: 'new',
		date: '2023년 1월 26일',
		desc: "The madness of death 는 1인칭 심리 공포 게임입니다. 집에서 탈출하고 데스 스톤의 저주를 풀기 위해 집을 탐험하세요. 앞으로 나아가기 위해 퍼즐을 풀어야 하고 어둠 속에 머물지 않으려고 노력해야 합니다.",
		price: 5500,
		discount: 0,
  },
  {
		id: 'g_94',
		image: process.env.PUBLIC_URL+'/images/g94.jpg',
		name: "ONION ASSAULT",
		tag01: '액션',
		tag02: '2D',
    tag03: '플랫폼',
		tag04: '오브젝트',
		tag05: '컨트롤러',
		tag06: 'best',
		date: '2023년 1월 26일',
		desc: "The evil Croquetto Empire is trying to conquer Onionia and it's up to one brave onion farmer, and his mom, to stop the tyrannical invading fascist army! Old-school 2D platfoming from the creator of Gunman Clive and Mechstermination Force.",
		price: 8900,
		discount: 0,
  },
  {
		id: 'g_95',
		image: process.env.PUBLIC_URL+'/images/g95.jpg',
		name: "THE CALLISTO PROTOCOL™",
		tag01: '공포',
		tag02: '공상과학',
    tag03: '생존',
		tag04: '우주',
		tag05: '컨트롤러',
		date: '2022년 12월 2일',
		desc: "반드시 살아남아 칼리스토의 공포에서 벗어나고, 목성의 '죽은 달' 칼리스토의 어두운 비밀을 밝혀내십시오.",
		price: 74800,
		discount: 0,
  },
  {
		id: 'g_96',
		image: process.env.PUBLIC_URL+'/images/g96.jpg',
		name: "MAKIS ADVENTURE",
		tag01: '2D',
		tag02: '액션',
    tag03: '탐험',
		tag04: '픽셀 그래픽',
		tag05: '컨트롤러',
		date: '2023년 1월 19일',
		desc: "Fight, dash, swim and bite your way through 3 different dungeons. Let the inner shark out! Face many different opponents and defeat powerful bosses. Makis Adventure is a pixel art platformer with a bite!",
		price: 11000,
		discount: 0,
  },
  {
		id: 'g_97',
		image: process.env.PUBLIC_URL+'/images/g97.jpg',
		name: "HIGH ON LIFE",
		tag01: '1인칭',
		tag02: '슈팅',
    tag03: '코미디',
		tag04: '어드벤처',
		tag05: '컨트롤러',
		date: '2022년 12월 3일',
		desc: "High On Life는 저스틴 로일랜드의 아이디어에서 탄생했습니다. 인류를 마약으로 사용하려는 외계 조직이 인류의 미래를 위협하고 있습니다. ",
		price: 61000,
		discount: 0,
  },
  {
		id: 'g_98',
		image: process.env.PUBLIC_URL+'/images/g98.jpg',
		name: "BIO PROTOTYPE",
		tag01: '액션',
		tag02: '로그라이크',
    tag03: '픽셀',
		tag04: '2D',
		tag05: '컨트롤러',
		date: '2022년 12월 17일',
		desc: "A wave of irrational experimentation rushes towards you. Hurry up and mutate! evolution! Become scarier monsters than them!",
		price: 3400,
		discount: 0,
  },
  {
		id: 'g_99',
		image: process.env.PUBLIC_URL+'/images/g99.jpg',
		name: "CATCH ME!",
		tag01: '액션',
		tag02: '2D',
    tag03: '스포츠',
		tag04: '만화',
		tag05: '컨트롤러',
		tag06: 'best',
		date: '2023년 1월 24일',
		desc: "Compete online against your friends and other players in this chaotic and fast paced 4-player game of tag! Race across different locations, jump through windows, electrocute the other players or throw cats at them.",
		price: 11000,
		discount: 0,
  },
  {
		id: 'g_100',
		image: process.env.PUBLIC_URL+'/images/g100.jpg',
		name: "HYPER SHAPES",
		tag01: '탄막',
		tag02: '아케이드',
    tag03: '액션',
		tag04: '슈팅',
		tag05: '컨트롤러',
		date: '2023년 1월 24일',
		desc: "Hyper Shapes is a frenetic minimalist Boss Rush where understanding the enemies attack patterns and weaknesses is key.",
		price: 5600,
		discount: 0.1,
  }  
]

export default game;